### PR TITLE
Git Deploy Key Automation

### PR DESCRIPTION
**Pull request by KYTG-Dev**

### CODE REVIEW

**Comment by BellaNotte1986** [comment]
Code is looking great so far. 2 Quick questions/requests
1. The deploy key generally gets added at the project level in gitlab. Will the commands work if I use a project ID where it cals for the group id?
2. Can the functions be updated to take a list of projects to add a single deploy key?

**Comment by KYTG-Dev** [comment]
Add or remove deploy keys to GitLab projects based on input.

The script now includes the following features:

- Ability to add or remove deploy keys for specific or list of project IDs.
- Recursive search for projects within groups:
  - Providing a group ID will include all projects within that group for key addition or removal.
  - Adding the recursive flag along with a group ID will include all projects within the main group and its subgroups.
- Support for GITLAB_TOKEN and GITLAB_DEPLOY_KEY environment variables.

**Comment by BellaNotte1986** [comment]
Final question. If a Deploy Key is already added to a project within a subgroup, I can generally enable that deploy key instead of readding or disable it if enabled without deleting it. Do the add and remove API calls account for this case?

**Comment by KYTG-Dev** [comment]
In the latest version of Gitlab's API these cases are covered without additional logic:

**Behavior of the add:**

- If an existing deploy key value is the same as the deploy key value to add, it will not re-create the key, it will enable the existing key to the project with status code 201

- If deploy key is already added and enabled to the project, the add will not throw an error. The key will also not be re-created, but will be re-enabled to the project with status code 201

**Behavior of the remove** 

- GitLab API does not have seperate options for disable or delete, the remove behavior matches the GitLab API behavior where if a deploy key is used by multiple projects the current project will disable the deploy key. If a deploy key is only used by the current project it will be deleted. More info below...

From Gitlab API  Documentation: [Revoking a Deploy Key](https://docs.gitlab.com/ee/user/project/deploy_keys/#revoke-project-access-of-a-deploy-key)

>
>What happens to the deploy key when it is disabled depends on the following:
>
>If the key is publicly accessible, it is removed from the project but still available in the Publicly accessible deploy keys tab.
>If the key is privately accessible and only in use by this project, it is deleted.
>If the key is privately accessible and also in use by other projects, it is removed from the project, but still available in the privately accessible deploy keys tab.
>

**Comment by KYTG-Dev** [comment]
Commit Changes:

- Added expires_at option for setting expiration of deploy key
- Added status code to export 
- Added ssh key value to compare when removing (previously only removed by name, now can remove based on ssh key or name), must set -D option in order to delete via deploy key
- Removed default deploy key name from remove, to prevent accidently removal if key name is not given
- Updated README.md

**Review by BellaNotte1986 — APPROVED** [review]
Looks great!

**Pull request merged**
